# Generated by Django 4.0.4 on 2022-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('idAnime', models.AutoField(primary_key=True, serialize=False)),
                ('nomeAnime', models.CharField(max_length=255)),
                ('descricaoAnime', models.TextField()),
                ('dataLancamento', models.DateTimeField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
