# Generated by Django 4.0.5 on 2022-06-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('idAnime', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('produtora', models.CharField(max_length=255)),
                ('dataLancamento', models.DateTimeField()),
            ],
        ),
    ]
